### ISSUE TITLE
YANG model tree diagram output

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#21]
Hi,
the YANG validator used to produce the tree diagram as one of its outputs. Now, as I've found, it does not. Can you please kindly bring back "-f tree"?

Regards,
Greg

**Comment by miroslavKovacPantheon** [comment]
Hello Greg,

yangvalidator tool only contains the output of validations since it has been moved under yangcatalog. But there is another tool in yangcatalog that you can use. If you check [this tool](https://www.yangcatalog.org/yang-search/module_details/) and you write the name of the desired module submit then you can see on the top there is tree view. Which is just fancy kind of -f tree or if you prefer the old output you can scroll down to tree output where you have link to the service that generated the pyang -f tree output. This is just an api you can use -> https://yangcatalog.org/api/services/tree/<name>@<revision>.yang

Is this sufficient for you?

**Comment by miroslavKovacPantheon** [comment]
I am closing this issue as there is no answer and there are tools that do this kind of output
